version: '2'
services:
  bot:
    env_file: .env
    build: .
    volumes:
      - .:/frc-team-update-bot
    command: python -u run.py
    depends_on:
      - db
  db:
    build: ./db
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "8001:5432"
